# Generated by Django 4.1.7 on 2023-04-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Field Options',
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastiflex_app.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastiflex_app.fields')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastiflex_app.fieldoption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastiflex_app.product')),
            ],
            options={
                'verbose_name_plural': 'Product Field Values',
            },
        ),
        migrations.AddField(
            model_name='fieldoption',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastiflex_app.fields'),
        ),
        migrations.CreateModel(
            name='CategoryFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastiflex_app.category')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastiflex_app.fields')),
            ],
            options={
                'verbose_name_plural': 'Category Field Values',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='fields',
            field=models.ManyToManyField(blank=True, through='mastiflex_app.CategoryFieldValue', to='mastiflex_app.fields'),
        ),
    ]
