# Generated by Django 4.1.7 on 2023-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastiflex_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/products/default.jpg', upload_to='img/products/'),
        ),
    ]
